[package]
name = "ootr-utils"
version = "0.1.14"
edition = "2021"

[dependencies]
async-proto = { version = "0.16.2", features = ["semver"] }
enum-iterator = "1.4.0"
git2 = "0.17"
itertools = "0.11"
lazy-regex = "2.4.1"
pyo3 = { version = "0.19", features = ["auto-initialize"], optional = true }
semver = "1.0.16"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
serde_plain = "1.0.1"
sqlx = { version = "0.7", optional = true, features = ["runtime-tokio-rustls"] }
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["process"] }
wheel = { git = "https://github.com/fenhl/wheel", branch = "main" }

[target."cfg(unix)".dependencies]
xdg = "2.4.1"

[target."cfg(windows)".dependencies]
directories = "5"
