[package]
name = "ootr-utils"
version = "0.1.6"
edition = "2021"

[dependencies]
async-proto = { version = "0.16.2", features = ["semver"] }
git2 = "0.16.1"
itertools = "0.10.5"
lazy-regex = "2.4.1"
pyo3 = { version = "0.18.0", features = ["auto-initialize"], optional = true }
semver = "1.0.16"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
serde_plain = "1.0.1"
sqlx = { version = "0.6.2", optional = true, features = ["runtime-tokio-rustls"] }
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["process"] }
wheel = { git = "https://github.com/fenhl/wheel", branch = "main", version = "0.8.2" }

[target."cfg(unix)".dependencies]
xdg = "2.4.1"

[target."cfg(windows)".dependencies]
directories = "4.0.1"
