[package]
name = "ootr-utils"
version = "0.2.9"
edition = "2021"

[dependencies]
async-proto = { version = "0.18", features = ["semver"] }
enum-iterator = "1.4.0"
git2 = "0.18"
itertools = "0.12"
lazy-regex = "3"
semver = "1.0.16"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
serde_plain = "1.0.1"
sqlx = { version = "0.7", optional = true, features = ["runtime-tokio-rustls"] }
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["parking_lot", "process"] }
wheel = { git = "https://github.com/fenhl/wheel", branch = "main" }

[target."cfg(unix)".dependencies]
xdg = "2.4.1"

[target."cfg(windows)".dependencies]
directories = "5"
