[package]
name = "ootr-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
async-proto = { version = "0.16.2", features = ["semver"] }
itertools = "0.10.5"
lazy-regex = "2.4.1"
pyo3 = { version = "0.18.0", features = ["auto-initialize"], optional = true }
semver = "1.0.16"
serde = "1.0.152"
serde_plain = "1.0.1"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["process"] }
wheel = { git = "https://github.com/fenhl/wheel", branch = "main", version = "0.8.2" }

[target."cfg(unix)".dependencies]
xdg = "2.4.1"

[target."cfg(windows)".dependencies]
directories = "4.0.1"
